// ============================================
// Central Store Exports
// ============================================

// Cart Store
export {
  $cart,
  $cartItems,
  $cartCount,
  $cartSubtotal,
  $cartDiscounts,
  $cartShipping,
  $cartTax,
  $cartTotal,
  $cartTotals,
  $hasAgeRestrictedItems,
  $estimatedWeight,
  $appliedPromotions,
  $appliedPromoCode,
  addToCart,
  updateQuantity,
  removeFromCart,
  clearCart,
  applyPromoCode,
  removePromoCode,
  validateStock,
  getItemById,
  incrementQuantity,
  decrementQuantity,
  formatPrice,
  isInCart,
  getQuantityInCart,
} from './cart'

// User Store
export {
  $user,
  $preferences,
  $authToken,
  $isLoading,
  $authError,
  $isAuthenticated,
  login,
  register,
  logout,
  updateProfile,
  changePassword,
  verifyEmail,
  requestPasswordReset,
  updatePreferences,
  setDefaultAddress,
  setDefaultPaymentMethod,
  toggleNewsletter,
  toggleSmsNotifications,
  addDietaryRestriction,
  removeDietaryRestriction,
  getFullName,
  getMembershipBadge,
  hasPermission,
} from './user'

// Addresses Store
export {
  $addresses,
  $selectedAddressId,
  $isLoadingAddresses,
  $addressError,
  $selectedAddress,
  $defaultAddress,
  $sortedAddresses,
  fetchAddresses,
  addAddress,
  updateAddress,
  deleteAddress,
  setDefaultAddress as setAddressDefault,
  selectAddress,
  clearAddressSelection,
  validateCoverage,
  formatAddress,
  getAddressById,
  hasAddresses,
  COMUNAS_SANTIAGO,
} from './addresses'

// Checkout Store
export {
  $checkoutStep,
  $deliverySlot,
  $paymentMethod,
  $invoiceData,
  $isProcessing,
  $checkoutError,
  $orderId,
  $canProceedToAddress,
  $canProceedToDelivery,
  $canProceedToPayment,
  $canPlaceOrder,
  $checkoutSummary,
  goToStep,
  nextStep,
  previousStep,
  fetchAvailableSlots,
  selectDeliverySlot,
  selectDeliveryDate,
  clearDeliverySlot,
  selectPaymentMethod,
  clearPaymentMethod,
  updateInvoiceData,
  toggleInvoice,
  clearInvoiceData,
  validateCheckout,
  placeOrder,
  resetCheckout,
  resetDeliveryAndPayment,
  getStepNumber,
  getTotalSteps,
  getStepProgress,
  formatTimeSlot,
  calculateEstimatedDelivery,
} from './checkout'

// Wishlist Store
export {
  $wishlist,
  $savedLists,
  $selectedListId,
  $wishlistItems,
  $wishlistCount,
  $selectedList,
  addToWishlist,
  removeFromWishlist,
  toggleWishlist,
  clearWishlist,
  moveToCart,
  moveAllToCart,
  updateWishlistNotes,
  createList,
  deleteList,
  renameList,
  addToList,
  removeFromList,
  clearList,
  selectList,
  shareList,
  unshareList,
  duplicateList,
  addListToCart,
  isProductInWishlist,
  isProductInList,
  getWishlistItem,
  getListById,
  getListByShareCode,
} from './wishlist'

// Search Store
export {
  $query,
  $filters,
  $sort,
  $suggestions,
  $isLoading as $isSearchLoading,
  $recentSearches,
  $hasActiveFilters,
  $activeFilterCount,
  setQuery,
  clearQuery,
  search,
  fetchSuggestions,
  addRecentSearch,
  removeRecentSearch,
  clearRecentSearches,
  setFilters,
  toggleCategory,
  toggleBrand,
  setPriceRange,
  toggleOnSale,
  toggleInStock,
  setMinRating,
  toggleDietary,
  toggleOrganic,
  clearFilters,
  clearFilter,
  setSort,
  applyFiltersToProducts,
  applySortToProducts,
  applyQuickFilter,
  SUPERMARKET_CATEGORIES,
  DIETARY_OPTIONS,
  SORT_OPTIONS,
} from './search'

// Re-export types
export type * from '../types/store.types'
